botToken: abcdef123456789
botUsername: sample_username
chats:
  - -1234567890123
serverStartMessage: 'Server started.'
serverStopMessage: 'Server stopped.'
logJoinLeave: true
logFromMCtoTG: true
logFromTGtoMC: true
logPlayerDeath: false
logPlayerAsleep: false
strings:
  online: '<b>Online</b>'
  nobodyOnline: '<b>Nobody online...</b>'
  joined: 'joined'
  left: 'left'
commands:
  time: '/time'
  online: '/online'